#!/usr/bin/env bash
set -euo pipefail
# Configuration
JOBS=$(nproc)
# Directories
HOME_DIR="$HOME"
WORK_DIR="${HOME_DIR}/build"
SRC_DIR="${HOME_DIR}/src"
SYSROOT_DIR="${HOME_DIR}/overlay"
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

if [ ! -d "${SRC_DIR}/linux" ]; then
    cd "${SRC_DIR}"
    git clone --depth 1 https://github.com/torvalds/linux.git
fi


if [ ! -d "${SRC_DIR}/llvm-project" ]; then
    cd "${SRC_DIR}"
    git clone --depth 1 https://github.com/SuperOptimizer/llvm-project.git
fi

mkdir -p "${WORK_DIR}/overlay-build"
cd "${WORK_DIR}/overlay-build"
cmake -G Ninja "${SRC_DIR}/llvm-project/llvm" \
-DLLVM_ENABLE_RUNTIMES="libc;compiler-rt;libunwind;libcxx;libcxxabi" \
-DLLVM_ENABLE_PROJECTS="clang;lld" \
-DCLANG_DEFAULT_CXX_STDLIB=libc++ \
-DCLANG_DEFAULT_LINKER=lld \
-DCLANG_DEFAULT_RTLIB=compiler-rt \
-DCLANG_DEFAULT_UNWINDLIB=libunwind \
-DCMAKE_BUILD_TYPE=Release \
-DCMAKE_CXX_COMPILER=clang++-21 \
-DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
-DCMAKE_CXX_STANDARD=20 \
-DCMAKE_C_COMPILER=clang-21 \
-DCMAKE_C_COMPILER_LAUNCHER=ccache \
-DCMAKE_INSTALL_PREFIX="${SYSROOT_DIR}" \
-DCMAKE_TARGET_TRIPLE="x86_64-linux-gnu" \
-DCOMPILER_RT_BUILD_BUILTINS=ON \
-DCOMPILER_RT_BUILD_CRT=ON \
-DCOMPILER_RT_BUILD_GWP_ASAN=ON                       \
-DCOMPILER_RT_BUILD_LIBFUZZER=ON \
-DCOMPILER_RT_BUILD_MEMPROF=ON \
-DCOMPILER_RT_BUILD_ORC=ON \
-DCOMPILER_RT_BUILD_PROFILE=ON \
-DCOMPILER_RT_BUILD_SANITIZERS=ON        \
-DCOMPILER_RT_BUILD_SCUDO_STANDALONE_WITH_LLVM_LIBC=ON \
-DCOMPILER_RT_BUILD_XRAY=ON \
-DCOMPILER_RT_CXX_LIBRARY=libcxx \
-DCOMPILER_RT_ENABLE_STATIC_UNWINDER=ON \
-DCOMPILER_RT_ENABLE_THREADS=OFF \
-DCOMPILER_RT_SCUDO_STANDALONE_BUILD_SHARED=ON        \
-DCOMPILER_RT_STATIC_CXX_LIBRARY=ON \
-DCOMPILER_RT_USE_ATOMIC_LIBRARY=ON \
-DCOMPILER_RT_USE_BUILTINS_LIBRARY=ON \
-DCOMPILER_RT_USE_LLVM_UNWINDER=ON \
-DLIBCXXABI_ENABLE_ASSERTIONS=OFF \
-DLIBCXXABI_ENABLE_FORGIVING_DYNAMIC_CAST=ON \
-DLIBCXXABI_ENABLE_STATIC=ON \
-DLIBCXXABI_ENABLE_STATIC_UNWINDER=ON \
-DLIBCXXABI_ENABLE_THREADS=ON \
-DLIBCXXABI_USE_COMPILER_RT=ON \
-DLIBCXXABI_USE_LLVM_UNWINDER=ON \
-DLIBCXX_ABI_UNSTABLE=ON \
-DLIBCXX_ENABLE_EXCEPTIONS=ON \
-DLIBCXX_ENABLE_FILESYSTEM=ON \
-DLIBCXX_ENABLE_LOCALIZATION=ON \
-DLIBCXX_ENABLE_MONOTONIC_CLOCK=ON \
-DLIBCXX_ENABLE_RANDOM_DEVICE=ON \
-DLIBCXX_ENABLE_RTTI=OFF \
-DLIBCXX_ENABLE_SHARED=ON \
-DLIBCXX_ENABLE_STATIC=ON \
-DLIBCXX_ENABLE_STATIC_ABI_LIBRARY=ON \
-DLIBCXX_ENABLE_THREADS=ON \
-DLIBCXX_ENABLE_TIME_ZONE_DATABASE=ON \
-DLIBCXX_ENABLE_UNICODE=ON \
-DLIBCXX_ENABLE_WIDE_CHARACTERS=ON \
-DLIBCXX_HAS_MUSL_LIBC=OFF \
-DLIBCXX_HAS_TERMINAL_AVAILABLE=ON \
-DLIBCXX_INCLUDE_TESTS=OFF \
-DLIBCXX_STATICALLY_LINK_ABI_IN_STATIC_LIBRARY=ON \
-DLIBCXX_SUPPORTED_C_LIBRARIES=llvm-libc \
-DLIBCXX_SUPPORTED_HARDENING_MODES=none \
-DLIBCXX_USE_COMPILER_RT=ON \
-DLIBC_CONF_ERRNO_MODE=LIBC_ERRNO_MODE_SHARED \
-DLIBC_ENABLE_USE_BY_CLANG=ON \
-DLIBC_ENABLE_WIDE_CHARACTERS=ON \
-DLIBUNWIND_ENABLE_ASSERTIONS=OFF \
-DLIBUNWIND_ENABLE_PEDANTIC=OFF \
-DLIBUNWIND_ENABLE_SHARED=ON \
-DLIBUNWIND_ENABLE_STATIC=ON \
-DLIBUNWIND_ENABLE_THREADS=ON \
-DLIBUNWIND_USE_COMPILER_RT=ON \
-DLLVM_CCACHE_BUILD=ON \
-DLLVM_ENABLE_EH=OFF \
-DLLVM_ENABLE_EXPENSIVE_CHECKS=OFF \
-DLLVM_ENABLE_LIBCXX=ON \
-DLLVM_ENABLE_LIBPFM=ON \
-DLLVM_ENABLE_LLD=ON \
-DLLVM_ENABLE_LLVM_LIBC=ON \
-DLLVM_ENABLE_MODULES=OFF \
-DLLVM_ENABLE_RTTI=OFF \
-DLLVM_ENABLE_THREADS=ON \
-DLLVM_ENABLE_UNWIND_TABLES=ON \
-DLLVM_INCLUDE_BENCHMARKS=OFF \
-DLLVM_INCLUDE_EXAMPLES=OFF \
-DLLVM_ENABLE_FATLTO=ON \
-DLLVM_ENABLE_LTO=Full \
-DLLVM_INCLUDE_TESTS=OFF \
-DLLVM_INCLUDE_TOOLS=ON \
-DLLVM_INSTALL_UTILS=ON \
-DLLVM_LIBC_FULL_BUILD=OFF \
-DLLVM_LIBC_INCLUDE_SCUDO=ON \
-DLLVM_STATIC_LINK_CXX_STDLIB=ON \
-DLLVM_UNREACHABLE_OPTIMIZE=ON \
-DRUNTIMES_x86_64-linux-gnu_COMPILER_RT_BUILD_BUILTINS=ON \
-DRUNTIMES_x86_64-linux-gnu_COMPILER_RT_BUILD_CRT=ON \
-DRUNTIMES_x86_64-linux-gnu_COMPILER_RT_BUILD_GWP_ASAN=ON     \
-DRUNTIMES_x86_64-linux-gnu_COMPILER_RT_BUILD_LIBFUZZER=ON \
-DRUNTIMES_x86_64-linux-gnu_COMPILER_RT_BUILD_MEMPROF=ON \
-DRUNTIMES_x86_64-linux-gnu_COMPILER_RT_BUILD_ORC=ON \
-DRUNTIMES_x86_64-linux-gnu_COMPILER_RT_BUILD_PROFILE=ON \
-DRUNTIMES_x86_64-linux-gnu_COMPILER_RT_BUILD_SANITIZERS=ON        \
-DRUNTIMES_x86_64-linux-gnu_COMPILER_RT_BUILD_SCUDO_STANDALONE_WITH_LLVM_LIBC=ON \
-DRUNTIMES_x86_64-linux-gnu_COMPILER_RT_BUILD_XRAY=ON \
-DRUNTIMES_x86_64-linux-gnu_COMPILER_RT_CXX_LIBRARY=libcxx \
-DRUNTIMES_x86_64-linux-gnu_COMPILER_RT_ENABLE_STATIC_UNWINDER=ON \
-DRUNTIMES_x86_64-linux-gnu_COMPILER_RT_ENABLE_THREADS=OFF \
-DRUNTIMES_x86_64-linux-gnu_COMPILER_RT_SCUDO_STANDALONE_BUILD_SHARED=ON        \
-DRUNTIMES_x86_64-linux-gnu_COMPILER_RT_STATIC_CXX_LIBRARY=ON \
-DRUNTIMES_x86_64-linux-gnu_COMPILER_RT_USE_ATOMIC_LIBRARY=ON \
-DRUNTIMES_x86_64-linux-gnu_COMPILER_RT_USE_BUILTINS_LIBRARY=ON \
-DRUNTIMES_x86_64-linux-gnu_COMPILER_RT_USE_LLVM_UNWINDER=ON \
-DRUNTIMES_x86_64-linux-gnu_LIBCXXABI_ENABLE_ASSERTIONS=OFF \
-DRUNTIMES_x86_64-linux-gnu_LIBCXXABI_ENABLE_FORGIVING_DYNAMIC_CAST=ON \
-DRUNTIMES_x86_64-linux-gnu_LIBCXXABI_ENABLE_STATIC=ON \
-DRUNTIMES_x86_64-linux-gnu_LIBCXXABI_ENABLE_STATIC_UNWINDER=ON \
-DRUNTIMES_x86_64-linux-gnu_LIBCXXABI_ENABLE_THREADS=ON \
-DRUNTIMES_x86_64-linux-gnu_LIBCXXABI_USE_COMPILER_RT=ON \
-DRUNTIMES_x86_64-linux-gnu_LIBCXXABI_USE_LLVM_UNWINDER=ON \
-DRUNTIMES_x86_64-linux-gnu_LIBCXX_ABI_UNSTABLE=ON \
-DRUNTIMES_x86_64-linux-gnu_LIBCXX_ENABLE_EXCEPTIONS=ON \
-DRUNTIMES_x86_64-linux-gnu_LIBCXX_ENABLE_FILESYSTEM=ON \
-DRUNTIMES_x86_64-linux-gnu_LIBCXX_ENABLE_LOCALIZATION=ON \
-DRUNTIMES_x86_64-linux-gnu_LIBCXX_ENABLE_MONOTONIC_CLOCK=ON \
-DRUNTIMES_x86_64-linux-gnu_LIBCXX_ENABLE_RANDOM_DEVICE=ON \
-DRUNTIMES_x86_64-linux-gnu_LIBCXX_ENABLE_RTTI=OFF \
-DRUNTIMES_x86_64-linux-gnu_LIBCXX_ENABLE_SHARED=ON \
-DRUNTIMES_x86_64-linux-gnu_LIBCXX_ENABLE_STATIC=ON \
-DRUNTIMES_x86_64-linux-gnu_LIBCXX_ENABLE_STATIC_ABI_LIBRARY=ON \
-DRUNTIMES_x86_64-linux-gnu_LIBCXX_ENABLE_THREADS=ON \
-DRUNTIMES_x86_64-linux-gnu_LIBCXX_ENABLE_TIME_ZONE_DATABASE=ON \
-DRUNTIMES_x86_64-linux-gnu_LIBCXX_ENABLE_UNICODE=ON \
-DRUNTIMES_x86_64-linux-gnu_LIBCXX_ENABLE_WIDE_CHARACTERS=ON \
-DRUNTIMES_x86_64-linux-gnu_LIBCXX_HAS_MUSL_LIBC=OFF \
-DRUNTIMES_x86_64-linux-gnu_LIBCXX_HAS_TERMINAL_AVAILABLE=ON \
-DRUNTIMES_x86_64-linux-gnu_LIBCXX_INCLUDE_TESTS=OFF \
-DRUNTIMES_x86_64-linux-gnu_LIBCXX_STATICALLY_LINK_ABI_IN_STATIC_LIBRARY=ON \
-DRUNTIMES_x86_64-linux-gnu_LIBCXX_SUPPORTED_C_LIBRARIES=llvm-libc \
-DRUNTIMES_x86_64-linux-gnu_LIBCXX_SUPPORTED_HARDENING_MODES=none \
-DRUNTIMES_x86_64-linux-gnu_LIBCXX_USE_COMPILER_RT=ON \
-DRUNTIMES_x86_64-linux-gnu_LIBC_CONF_ERRNO_MODE=LIBC_ERRNO_MODE_SHARED \
-DRUNTIMES_x86_64-linux-gnu_LIBC_ENABLE_USE_BY_CLANG=ON \
-DRUNTIMES_x86_64-linux-gnu_LIBC_ENABLE_WIDE_CHARACTERS=ON \
-DRUNTIMES_x86_64-linux-gnu_LIBUNWIND_ENABLE_ASSERTIONS=OFF \
-DRUNTIMES_x86_64-linux-gnu_LIBUNWIND_ENABLE_PEDANTIC=OFF \
-DRUNTIMES_x86_64-linux-gnu_LIBUNWIND_ENABLE_SHARED=ON \
-DRUNTIMES_x86_64-linux-gnu_LIBUNWIND_ENABLE_STATIC=ON \
-DRUNTIMES_x86_64-linux-gnu_LIBUNWIND_ENABLE_THREADS=ON \
-DRUNTIMES_x86_64-linux-gnu_LIBUNWIND_USE_COMPILER_RT=ON

ninja
ninja install