#needs a recent llvm-toolchain. on ubuntu use https://apt.llvm.org/llvm.sh and download all packages for v 21

#!/usr/bin/env bash
set -euo pipefail
# Configuration
JOBS=$(nproc)
# Directories
HOME_DIR="$HOME"
WORK_DIR="${HOME_DIR}/build"
SRC_DIR="${HOME_DIR}/src"
SYSROOT_DIR="${HOME_DIR}/sysroot"
SYSROOT2_DIR="${HOME_DIR}/sysroot2"
TOOLCHAIN_DIR="${HOME_DIR}/toolchain"
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

# Create necessary directories
mkdir -p "${SRC_DIR}" "${WORK_DIR}" "${SYSROOT_DIR}"

# Clone repositories
cd "${SRC_DIR}"
if [ ! -d "llvm-project" ]; then
    git clone --depth 1 -c http.sslVerify=false https://github.com/SuperOptimizer/llvm-project.git
fi


# Clone Linux kernel and install headers
if [ ! -d "linux" ]; then
    git clone --depth 1 https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
fi

# Install Linux headers to sysroot
cd "${SRC_DIR}/linux"
make headers_install INSTALL_HDR_PATH="${SYSROOT_DIR}"


# DCMAKE_SYSROOT="$SYSROOT_DIR"
# Continue with the runtime build
mkdir -p "${WORK_DIR}/runtime-build"
cd "${WORK_DIR}/runtime-build"
cmake -G Ninja "${SRC_DIR}/llvm-project/llvm" \
-DCMAKE_CXX_FLAGS="   -w -fuse-ld=lld  -march=native -Os -g0" \
-DCMAKE_C_FLAGS="  -w -fuse-ld=lld -march=native -Os -g0" \
-DCMAKE_EXE_LINKER_FLAGS="  -fuse-ld=lld" \
-DBUILD_SHARED_LIBS=OFF \
-DCLANG_DEFAULT_CXX_STDLIB=libc++ \
-DCLANG_DEFAULT_LINKER=lld \
-DCLANG_DEFAULT_UNWINDLIB=libunwind \
-DCLANG_DEFAULT_RTLIB=compiler-rt \
-DCMAKE_BUILD_TYPE=MinSizeRel \
-DCMAKE_CXX_COMPILER=clang++-21 \
-DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
-DCMAKE_C_COMPILER=clang-21 \
-DCMAKE_C_COMPILER_LAUNCHER=ccache \
-DCMAKE_INSTALL_PREFIX="${SYSROOT_DIR}" \
-DCMAKE_LINKER=lld-21 \
-DLLVM_CCACHE_BUILD=ON \
-DLLVM_ENABLE_LLD=ON \
-DLLVM_ENABLE_PROJECTS="clang;lld" \
-DLLVM_ENABLE_RUNTIMES="libc;compiler-rt;libunwind;libcxx;libcxxabi" \
-DLLVM_LIBC_FULL_BUILD=ON \
-DLLVM_LIBC_INCLUDE_SCUDO=ON \
-DLIBC_KERNEL_HEADERS="${SYSROOT_DIR}/include" \
-DLLVM_RUNTIME_TARGETS="x86_64-linux-llvm" \
-DLLVM_STATIC_LINK_CXX_STDLIB=ON \
-DRUNTIMES_x86_64-linux-llvm_CMAKE_CXX_COMPILER=clang++-21 \
-DRUNTIMES_x86_64-linux-llvm_CMAKE_CXX_COMPILER_LAUNCHER=ccache \
-DRUNTIMES_x86_64-linux-llvm_CMAKE_CXX_FLAGS="   -w -fuse-ld=lld  -march=native -Os -g0" \
-DRUNTIMES_x86_64-linux-llvm_CMAKE_C_COMPILER=clang-21 \
-DRUNTIMES_x86_64-linux-llvm_CMAKE_C_COMPILER_LAUNCHER=ccache \
-DRUNTIMES_x86_64-linux-llvm_CMAKE_C_FLAGS="   -w -fuse-ld=lld  -march=native -Os -g0" \
-DRUNTIMES_x86_64-linux-llvm_CMAKE_EXE_LINKER_FLAGS="   -fuse-ld=lld" \
-DRUNTIMES_x86_64-linux-llvm_CMAKE_LINKER=lld-21 \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_BUILD_GWP_ASAN=OFF                       \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_BUILD_LIBFUZZER=OFF \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_BUILD_ORC=OFF \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_BUILD_PROFILE=OFF \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_BUILD_PROFILE=OFF \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_BUILD_SANITIZERS=ON        \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_BUILD_SCUDO_STANDALONE_WITH_LLVM_LIBC=ON \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_BUILD_XRAY=OFF \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_CXX_LIBRARY=libcxx \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_ENABLE_STATIC_UNWINDER=ON \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_SCUDO_STANDALONE_BUILD_SHARED=OFF        \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_STATIC_CXX_LIBRARY=ON \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_USE_ATOMIC_LIBRARY=ON \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_USE_BUILTINS_LIBRARY=ON \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_USE_LLVM_UNWINDER=ON \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_DEFAULT_TARGET_ONLY=ON \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_BUILTINS_ENABLE_PER_TARGET_RUNTIME_DIR=ON \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_BUILD_BUILTINS=ON \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_BUILD_CRT=ON \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_OS_DIR="linux-llvm" \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_BUILTINS_ENABLE_x86_64-unknown-linux-gnu=OFF \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_BUILTINS_ENABLE_x86_64-unknown-linux-llvm=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXXABI_ENABLE_ASSERTIONS=OFF \
-DRUNTIMES_x86_64-linux-llvm_LIBCXXABI_ENABLE_FORGIVING_DYNAMIC_CAST=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXXABI_ENABLE_STATIC=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXXABI_ENABLE_STATIC_UNWINDER=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXXABI_STATICALLY_LINK_UNWINDER_IN_STATIC_LIBRARY=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXXABI_USE_COMPILER_RT=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXXABI_USE_LLVM_UNWINDER=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_ABI_UNSTABLE=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_ENABLE_EXCEPTIONS=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_ENABLE_FILESYSTEM=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_ENABLE_LOCALIZATION=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_ENABLE_MONOTONIC_CLOCK=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_ENABLE_RANDOM_DEVICE=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_ENABLE_RTTI=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_ENABLE_SHARED=OFF \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_ENABLE_STATIC=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_ENABLE_STATIC_ABI_LIBRARY=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_ENABLE_THREADS=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_ENABLE_UNICODE=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_ENABLE_WIDE_CHARACTERS=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_HAS_TERMINAL_AVAILABLE=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_INCLUDE_TESTS=OFF \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_STATICALLY_LINK_ABI_IN_STATIC_LIBRARY=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_SUPPORTED_C_LIBRARIES=system \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_SUPPORTED_HARDENING_MODES=none \
-DRUNTIMES_x86_64-linux-llvm_LIBC_ENABLE_USE_BY_CLANG=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBUNWIND_ENABLE_ASSERTIONS=OFF \
-DRUNTIMES_x86_64-linux-llvm_LIBUNWIND_ENABLE_PEDANTIC=OFF \
-DRUNTIMES_x86_64-linux-llvm_LIBUNWIND_ENABLE_SHARED=OFF \
-DRUNTIMES_x86_64-linux-llvm_LIBUNWIND_ENABLE_STATIC=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBUNWIND_USE_COMPILER_RT=ON \
-DRUNTIMES_x86_64-linux-llvm_LLVM_LIBC_FULL_BUILD=ON \
-DRUNTIMES_x86_64-linux-llvm_LLVM_LIBC_INCLUDE_SCUDO=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBC_KERNEL_HEADERS="${SYSROOT_DIR}/include" \
-DRUNTIMES_x86_64-linux-llvm_SANITIZER_USE_STATIC_CXX_ABI=ON \
-DRUNTIMES_x86_64-linux-llvm_SANITIZER_USE_STATIC_LLVM_UNWINDER=ON


ninja -k 0
ninja -k 0 install

mkdir -p "${WORK_DIR}/toolchain-build"
cd "${WORK_DIR}/toolchain-build"
cmake -G Ninja "${SRC_DIR}/llvm-project/llvm" \
-DCMAKE_TOOLCHAIN_FILE="${SCRIPT_DIR}/x86_64-linux-llvm.cmake" \
-DCMAKE_CXX_FLAGS=" -target x86_64-linux-llvm -static  -w -fuse-ld=lld --rtlib=compiler-rt -unwind=libunwind -stdlib=libc++  -march=native -Os -g0" \
-DCMAKE_C_FLAGS=" -target x86_64-linux-llvm -static -w -fuse-ld=lld --rtlib=compiler-rt -unwind=libunwind  -march=native -Os -g0" \
-DCMAKE_EXE_LINKER_FLAGS=" -target x86_64-linux-llvm -static -fuse-ld=lld --rtlib=compiler-rt -unwind=libunwind -stdlib=libc++ " \
-DBUILD_SHARED_LIBS=OFF \
-DCLANG_DEFAULT_CXX_STDLIB=libc++ \
-DCLANG_DEFAULT_LINKER=lld \
-DCLANG_DEFAULT_UNWINDLIB=libunwind \
-DCLANG_DEFAULT_RTLIB=compiler-rt \
-DCMAKE_BUILD_TYPE=MinSizeRel \
-DCMAKE_CXX_COMPILER="${SYSROOT_DIR}/bin/clang++" \
-DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
-DCMAKE_C_COMPILER="${SYSROOT_DIR}/bin/clang++" \
-DCMAKE_C_COMPILER_LAUNCHER=ccache \
-DCMAKE_INSTALL_PREFIX="${SYSROOT2_DIR}" \
-DCMAKE_LINKER="${SYSROOT_DIR}/bin/lld" \
-DLLVM_CCACHE_BUILD=ON \
-DLLVM_ENABLE_LLD=ON \
-DLLVM_ENABLE_PROJECTS="clang;lld" \
-DLLVM_ENABLE_RUNTIMES="libc;compiler-rt;libunwind;libcxx;libcxxabi" \
-DLLVM_LIBC_FULL_BUILD=ON \
-DLLVM_LIBC_INCLUDE_SCUDO=ON \
-DLIBC_KERNEL_HEADERS="${SYSROOT_DIR}/include" \
-DLLVM_RUNTIME_TARGETS="x86_64-linux-llvm" \
-DLLVM_STATIC_LINK_CXX_STDLIB=ON \
-DRUNTIMES_x86_64-linux-llvm_CMAKE_CXX_COMPILER="${SYSROOT_DIR}/bin/clang++" \
-DRUNTIMES_x86_64-linux-llvm_CMAKE_CXX_COMPILER_LAUNCHER=ccache
-DRUNTIMES_x86_64-linux-llvm_CMAKE_CXX_FLAGS="   -w -fuse-ld=lld  -march=native -Os -g0" \
-DRUNTIMES_x86_64-linux-llvm_CMAKE_C_COMPILER="${SYSROOT_DIR}/bin/clang" \
-DRUNTIMES_x86_64-linux-llvm_CMAKE_C_COMPILER_LAUNCHER=ccache
-DRUNTIMES_x86_64-linux-llvm_CMAKE_C_FLAGS="   -w -fuse-ld=lld  -march=native -Os -g0" \
-DRUNTIMES_x86_64-linux-llvm_CMAKE_EXE_LINKER_FLAGS="   -fuse-ld=lld" \
-DRUNTIMES_x86_64-linux-llvm_CMAKE_LINKER="${SYSROOT_DIR}/bin/lld" \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_BUILD_GWP_ASAN=OFF                       \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_BUILD_LIBFUZZER=OFF \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_BUILD_ORC=OFF \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_BUILD_PROFILE=OFF \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_BUILD_PROFILE=OFF \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_BUILD_SANITIZERS=ON        \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_BUILD_SCUDO_STANDALONE_WITH_LLVM_LIBC=ON \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_BUILD_XRAY=OFF \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_CXX_LIBRARY=libcxx \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_ENABLE_STATIC_UNWINDER=ON \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_SCUDO_STANDALONE_BUILD_SHARED=OFF        \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_STATIC_CXX_LIBRARY=ON \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_USE_ATOMIC_LIBRARY=ON \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_USE_BUILTINS_LIBRARY=ON \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_USE_LLVM_UNWINDER=ON \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_DEFAULT_TARGET_ONLY=ON \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_BUILTINS_ENABLE_PER_TARGET_RUNTIME_DIR=ON \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_BUILD_BUILTINS=ON \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_BUILD_CRT=ON \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_OS_DIR="linux-llvm" \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_BUILTINS_ENABLE_x86_64-unknown-linux-gnu=OFF \
-DRUNTIMES_x86_64-linux-llvm_COMPILER_RT_BUILTINS_ENABLE_x86_64-unknown-linux-llvm=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXXABI_ENABLE_ASSERTIONS=OFF \
-DRUNTIMES_x86_64-linux-llvm_LIBCXXABI_ENABLE_FORGIVING_DYNAMIC_CAST=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXXABI_ENABLE_STATIC=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXXABI_ENABLE_STATIC_UNWINDER=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXXABI_STATICALLY_LINK_UNWINDER_IN_STATIC_LIBRARY=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXXABI_USE_COMPILER_RT=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXXABI_USE_LLVM_UNWINDER=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_ABI_UNSTABLE=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_ENABLE_EXCEPTIONS=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_ENABLE_FILESYSTEM=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_ENABLE_LOCALIZATION=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_ENABLE_MONOTONIC_CLOCK=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_ENABLE_RANDOM_DEVICE=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_ENABLE_RTTI=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_ENABLE_SHARED=OFF \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_ENABLE_STATIC=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_ENABLE_STATIC_ABI_LIBRARY=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_ENABLE_THREADS=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_ENABLE_UNICODE=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_ENABLE_WIDE_CHARACTERS=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_HAS_TERMINAL_AVAILABLE=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_INCLUDE_TESTS=OFF \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_STATICALLY_LINK_ABI_IN_STATIC_LIBRARY=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_SUPPORTED_C_LIBRARIES=system \
-DRUNTIMES_x86_64-linux-llvm_LIBCXX_SUPPORTED_HARDENING_MODES=none \
-DRUNTIMES_x86_64-linux-llvm_LIBC_ENABLE_USE_BY_CLANG=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBUNWIND_ENABLE_ASSERTIONS=OFF \
-DRUNTIMES_x86_64-linux-llvm_LIBUNWIND_ENABLE_PEDANTIC=OFF \
-DRUNTIMES_x86_64-linux-llvm_LIBUNWIND_ENABLE_SHARED=OFF \
-DRUNTIMES_x86_64-linux-llvm_LIBUNWIND_ENABLE_STATIC=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBUNWIND_USE_COMPILER_RT=ON \
-DRUNTIMES_x86_64-linux-llvm_LLVM_LIBC_FULL_BUILD=ON \
-DRUNTIMES_x86_64-linux-llvm_LLVM_LIBC_INCLUDE_SCUDO=ON \
-DRUNTIMES_x86_64-linux-llvm_LIBC_KERNEL_HEADERS="${SYSROOT_DIR}/include" \
-DRUNTIMES_x86_64-linux-llvm_SANITIZER_USE_STATIC_CXX_ABI=ON \
-DRUNTIMES_x86_64-linux-llvm_SANITIZER_USE_STATIC_LLVM_UNWINDER=ON


ninja
ninja install
